let testi = [
    "Deserting lucid daydreaming.",
    "Bonjour bonsai.",
    "Bonsoir baobab.",
    "Fear under the armor.",
    "Fever in the calm.",
    "2B3.",
    "I will never be free if I am not free now.",
    "I have two loves: Physics and the Desert.",
    "A star is as far as the eye can see and as near as my eye is to me.",
    "As far as the eye can see: space immense transparent.",
    "Se dio non è qui, non è da nessuna parte, questo istante è la perfezione.",
    "3 suited men in my coffeshop: one of them just said: «My personal idea of progress is moving things forward» which is actually just the definition of progress. Everyone nudding. Guys like this are in charge of every industry and it's clearly why trains explode.",
    "She nose.",
    "I am ear.",
    "I mouth.",
    "She nose I am ear, satelleyes around. I mouth, see you lighter.",
    "I forgot to forget.",
    "There is nothing stranger than another alphabet.",
    "Se non sai cos'è allora è un avverbio.",
    "I am a musician 2.",
    "Solarscape.",
    "who? U.",
    "Tutto muove. Dove?",
    "Stop step totem.",
    "In the melted emptiness we invented this brown in which we drown we dance in the dense void we sense.",
    "Democrazy.",
    "Democrasky.",
    "Any sufficiently advanced technology is indistinguishable from magic.",
    "Il mio superiore, e anche lui ha il suo, se non sbaglio.",
    "Parola, signore possente che con piccolissimo corpo e invisibilissimo, divinissime cose sa compiere. Vai, cucciolo di cimice, esplori i vetri come fossero mondi!",
    "All I care about is the safety of my beautiful parallel feet.",
    "They keep asking questions.",
    "I am the taste in water.",
    "I am the light in fire.",
    "what is low and what is eight?",
    "Silent music.",
    "Are u hungry?",
    "Are you angry?",
    "How many stars?",
    "How many planets?",
    "Dark paintings.",
    "Paintings of pure light.",
    "The smell of bread.",
    "The cathegories of being.",
    "Mute poems.",
    "Universe large-scale structure.",
    "How many planes?",
    "The colour of water.",
    "The volume of a solid.",
    "Do you have news from the void?",
    "Geography.",
    "How many atoms?",
    "The taste of salt.",
    "They ask me if it is really possible to relieve the itching with the dagger.",
    "Whether two propellers perpendicular to each other are enough to make a helicopter.",
    "They put their hand in the pockets and stare at me.",
    "How many fingers?",
    "What am I touching?",
    "No doubt, the sooner the better: you can have a coffee. Doubn't, the more the loner: you can have a joint in the traffic jam.",
    "Every roll on returns a hair.",
    "Qual è il valore di un millimetro del tempo mio?",
    "Qual è il valore di un byte del mio spazio?",
    "Qual è il valore di un litro del mio pensiero?",
    "Tutti sanno che una formica non può spostare un albero della gomma.",
    "Non so se questo recinto mi voglia escludere oppure contenere.",
    "«Parli britannico?» mi domandò. «Jawol» I said.",
    "Un giorno sei nata il giorno dopo si muore di fame.",
    "Linguaggio, pipistrello pendulo dai propri piedi. Universo che si impedisce di precipitare nel nulla reggendosi alle proprie mani allacciate. Assoluta contraddizione che è tuttavia l'unica sede abitabile.",
    "There's no such happiness, there's no such emptiness.",
    "Perchè mi dici sempre no? Tergicristallo.",
    "Cosa porteresti su un'isola deserta? Un'isola deserta.",
    "You patrol both sides of the borders.",
    "When you feel free because you lack the very language to articulate your unfreedom.",
    "With four parameters I can fit an elephant, and with five I can make him wiggle his trunk.",
    "Rimane di questo abbaglio, che ci prese una mattina sulla strada per il nucleo, un suono continuo, come di cuculo. Sul ciglio esplodono, non sono granate bensì due fiori d'aglio.",
    "That is why you fight. You are nothing but animals that defend themselves, even when you attack. Come on, babies, be brave, life is war and war is life. FREEDOM DOES NOT EXIST.",
    "Su 10 cellule del nostro corpo 9 sono cellule di batteri.",
    "I giornalisti ovvero le parodie viventi dell'intelligenza.",
    "Pulsa, stupito e curioso cervello! Lancia domande e risposte! Qui ed ovunque resta sospeso, eterno flusso delle soluzioni!",
    "Ei fu siccome immobile prese l'automobile e si fece un altro giro.",
    "Gli eserciti sbarcano, le persone approdano.",
    "Sirio in una notte limpida, senza Luna e possibilmente senza i pianeti più luminosi, è pure in grado di proiettare a terra una leggerissima ombra degli oggetti.",
    "Made my dog listen to this now its a dog but confused.",
    "Padre, se anche tu non fossi il mio padre, se anche fossi a me un estraneo per te stesso egualmente t'amerei.",
    "Madre, se anche tu non fossi la mia madre, se anche fossi a me un'estranea per te stessa egualmente t'amerei.",
    "Bobby Fischer fece quattro mosse consecutive di Re in apertura.",
    "Ma cosa credi? Di essere attaccato ad un altoparlante? Cosa credi? Che la gente si debba chinare per riuscire a sentirti?",
    "10 thousand billion de futurs possibles.",
    "Il minuto ondulava insieme al vento.",
    "I lontani futuri violati dalla nostra presenza.",
    "There is nothing I regret you still undo the inner knots with your song.",
    "Won't bow down: dunno how!",
    "Senses I got no, no sense, I am unlimited!",
    "This is the HAND.",
    "This is the AND.",
    "This is the END.",
    "Pensavo è bello che dove finiscono le mie dita debba in qualche modo incominciare un computer.",
    "Da che parte stai, piccolo? - cercava di sapere. - In quale schieramento? Quello dei ribelli o quello di chi spinge a ribellarsi?",
    "Il polipo che insinua tentacoli d'inchiostro tra gli scogli può servirsi di te. Tu gli appartieni e non lo sai. Sei lui, ti credi te.",
    "Max relax.",
    "Super stress.",
    "C'è un uomo che chiede l'elemosina di fronte a un palazzo splendido. Il palazzo è suo.",
    "Let me be the chapel bell ringing at my birth.",
    "Anche parlando la stessa lingua io e la tigre non riuscimmo a capirci.",
    "In caso di bombardamento la cosa migliore è essere la bomba.",
    "Companies pay apps to show ads we pay apps to hide ads.",
    "So I started drawing before I was able to write. Obvious, but I had forgotten.",
    "D'altronde sono sempre gli altri che muoiono.",
    "Morto un povero se ne fa morire un altro.",
    "Il nemico è la differenza etica: un estraneo da negare nella sua totalità esistenziale.",
    "Per restare immobile l'ape deve muoversi velocissima.",
    "We must remember that god is entirely mouth.",
    "Rinunciare a qualsiasi ricchezza (a parte il computer!) perché per difenderla servirebbe una spada.",
    "Passa l'ultima greggia nella nebbia del suo fiato.",
    "Muri di luce.",
    "Sudokus complete themselves when you pass by.",
    "In the warm hole of your love.",
    "In the wormhole of your love.",
    "All things are a part.",
    "All things are apart.",
    "Tutti i vari modi in cui è possibile illuminare un cilindro qualsiasi.",
    "Does the archer fear his bow? Or does he kiss each arrow goodbye as it marries the wind?",
    "The only winner today is the Voyager probe, which is speeding away from Earth at 61.500 km/h.",
    "Do you know what I do when I see a spider in my house? Fucking nothing.",
    "Uno sputo per chi ha sete.",
    "La pioggia lo bagna, il vento lo asciuga.",
    "Ultimamente i momenti migliori sono quelli in cui vengo morso da un ragno.",
    "Sono il vestito del mio vestito.",
    "Quando un bullo fa pena, vuol dire che ha già perso.",
    "Adesso che ci penso, avrei molta più difficoltà a spiegare la magia in italiano a un italiano, quindi, in rapporto alla magia, posso fare qualunque cosa, anche toccare un ragno, o presentarmi a una ragazza, anche toccare una ragazza, presentarmi a un ragno.",
    "I am the landscape: surprise, bewilderment, shock.",
    "The material nature consists of three moods: goodness, passion, ignorance.",
    "E poi una trave nella ragione si spezzò, e io caddi giù, e più giù - e battei un mondo, a ogni tuffo, e finii di conoscere in quel punto.",
    "Spigolo della prua di una nave.",
    "Prua dello spigolo del tavolo.",
    "Naso, tu mi ha fatto indietreggiare all'odore della merda.",
    "Orecchio, quando il suono è forte dici agli occhi di chiudersi: non ho mai davvero visto il frastuono.",
    "Noi possiamo stare dappertutto e veniamo fuori dal niente.",
    "Punto, linea, superficie.",
    "Posto, lista, superfila.",
    "Pugno, lingua, supersfinge.",
    "Porta, limbo, superpasso.",
    "Ciò che chiamo poesia è spesso chiamato contenuto, io invece l'ho chiamato forma.",
    "Che chiosa vuoi da me?",
    "Can't ouch me!",
    "I hope I die before I get sold.",
    "Come with me imagination.",
    "La crosta di sale che sono diventato, una stalagmite di indifferenza.",
    "Questo sole doloroso che anche la mia ombra rifiuta di affrontare.",
    "Troppo pesante da portare, troppo leggero da resistere al viaggio.",
    "La lontananza è molta di più della semplice distanza.",
    "Non siamo le nostre aspettative, siamo le nostre attese.",
    "L'aggressività strategica dell'essere umano.",
    "Per le grandi menti del profitto, una città ridotta in macerie non è un cimitero, ma un mercato vergine.",
    "Il collasso del diritto.",
    "Questa minoranza di codardi.",
    "Tutti sotto il Cielo non appartengono a un solo uomo. Tutti sotto il Cielo significano quello che sono: Tutti sotto il Cielo.",
    "In un chilo di riso, trentacinquemila chicchi.",
    "Sembra impossibile dimenticare un autovelox.",
    "Gli ultimi tre mesi sono stati i più assurdi della mia vita, a pensarci bene è così ogni ultimi tre mesi.",
    "Quando scendo dall'autobus ho sempre l'impressione di essere la sua cacca.",
    "Tu sei il classico tipo che se va in guerra è contento: perché sta dietro.",
    "Spostare denaro da una tasca ad un'altra non è economia reale.",
    "Difficile ammettere quanto mi faccia bene lavorare.",
    "Che coraggio annusare il latte per sapere se è buono.",
    "Ultimamente mi sento sempre un po' abbronzato, sarà il computer.",
    "Il capitalismo odierno funziona sempre più come l'istituzionalizzazione dell'invidia.",
    "Quando il dottor Johnson batté il pugno sul tavolo sentì le conseguenze del tavolo. Questo fu l'unico modo in cui quel tavolo esistette.",
    "Non vogliamo il potere, vogliamo solo uno spazio libero al di fuori del vostro controllo dove poter portare avanti una riflessione critica su ciò che accade nella società.",
    "Ciò a cui mi oppongo è la percezione del razzismo come un problema di intolleranza. Perché tanti problemi sono oggi considerati problemi di intolleranza, invece che problemi di disuguaglianza, sfruttamento o ingiustizia? Perché è la tolleranza che si propone come rimedio.",
    "Le nostre cellule contengono tra i ventimila e i venticinquemila geni, ma si stima che i microbi dentro di noi ne abbiano cinquecento volte di più.",
    "Il movimento nell'acqua della maggior parte di questi animaletti era così rapido e vario - verso l'alto, verso il basso e in tondo - da essere meraviglioso a vedersi.",
    "Il microbo dice ai topi come usare i loro stessi geni per costruire un intestino sano.",
    "Almeno la metà della dopamina presente nel nostro corpo si trova nell'intestino, così come il 90% della serotonina.",
    "Mia madre è morta quando avevo sette anni, ha lasciato cinque bambini. Da allora ho incominciato a far ballare la marmotta.",
    "Mio nonno mi diceva: «Povero te, c'era la cavalleria ungherese, la più trista quando veniva alla carica, faceva dei flagelli...». Piangeva mentre raccontava, come faccio io adesso che ripenso alla mia guerra.",
    "Abbiamo bevuto quel brodo, e poi abbiamo mangiato il topo. Ve lo dico in verità di Dio che non è una bugia che mi invento.",
    "Erano personaggi importanti per confessare le donne, per convincerle. «Mai mettere quella materia fuori da quella porta», dicevano alle donne sposate, la contavano sempre così, loro erano per le famiglie numerose.",
    "I giovani sono tutti in fabbrica, ma se il lavoro cessa non so cosa faranno. A forza di fare macchine, 'ste fabbriche...",
    "Le guerre le fanno solo per distruggere.",
    "Sì che credevamo nelle masche. A messa le masche voltano la schiena all'altare, quando il prete si presenta con il Santissimo.",
    "Vede nel vallone un chiaro, una luce: Titu si dice: «Questa sarà sicuro la pietra preziosa del rospo», perché si credeva che i rospi avessero una pietra preziosa nel collo. Titu abbandona la mulattiera.",
    "Noialtri avevamo l'interesse della guerra? Gli ufficiali ci parlavano della patria. Noialtri quando potevamo avere la licenza e venire a casa la patria era quella lì.",
    "Adesso che abbiamo nominato le masche dobbiamo dire il giorno, dobbiamo dire che oggi è martedì, e non sbagliarci se no le masche potrebbero farci del male. Così mi hanno insegnato i miei vecchi.",
    "Che il Signore mi possa far perdere gli occhi, che ne ho cinque di famiglia, se non dico il vero.",
    "La terra rendeva quattro quintali di grano per giornata, adesso ne fanno diciotto, su due giornate doveva magari vivere una famiglia di dieci figli.",
    "L'episodio di Pasquale Roggero dice quanto fosse breve il passo verso la diserzione: dice inoltre che il nostro contadino-soldato, prima di disertare, ci pensava su mille volte.",
    "Le masche erano il male, le masche sapevano leggere, le masche «lavoravano di fisica» e distribuivano il malocchio.",
    "Le donne anziane e vecchie di Vignolo ricordano ancora con simpatia e riconoscenza un personaggio favoloso, Cin 'd Luleta, l'omino sgraziato che passava da una nutrice all'altra a püpé le done, a succhiare il latte troppo abbondante.",
    "Nelle nostre valli non sono in funzione le «camere a gas», così l'immagine del genocidio appare forse eccessiva alla folla dei «benpensanti», dei turisti distratti, dei gerarchi dispensatori di elemosine, dei colonialisti. Ma i fatti parlano, e dicono che non c'è più spazio per gli ignoranti.",
    "Ma chi vuole comprendere a fondo la storia di Castelmagno deve osservare la grande lapide di marmo che ricorda i sessantadue morti in guerra.",
    "C'era sempre il pericolo che incontrasse i cinghiali. Suo padre e sua madre urlavano mentre lui scendeva, uh uh uh, e lui rispondeva. La stessa storia quando tornava su alla sera: Gian Piero urlava e da Pragudin i genitori rispondevano.",
    "I francesi capivano il patois, ma non capivano il gergun, che funzionava così da linguaggio «cifrato», di difesa.",
    "Se avessero vissuto un attimo solo della nostra ritirata.",
    "Ricorda tutto di questo immenso massacro contadino.",
    "Nel preparare per le stampe le Memorie non sono stato aiutato da nessuno; non sto a fare i nomi di coloro che mi sono stati di ostacolo, perché ciò occuperebbe troppo posto.",
    "Arthur conosceva quel cane, e lo conosceva bene. Apparteneva a un suo amico pubblicitario e si chiamava Baluba-Zucca-Vuota il Cane Pirla, perché il groviglio di peli ritti che aveva sulla testa ricordavano alla gente il presidente degli Stati Uniti d'America.",
    "Il computer era di grandezza normale, considerato che era stato costruito nello spazio. Doveva avere all'incirca un'apertura di millecinquecento chilometri. Ciò che faceva girare la testa era che un simile computer sembrasse, per illusione ottica, posato su un divano che misurava al massimo due metri.",
    "Ma si tratta in realtà di un tempo passato, presente o futuro? Dipende da quale direzione, ascendente o discendente, si ritiene di dover dare alla storia: anche questo è un problema più che mai dibattuto, al momento.",
    "Un mago passò a zonzo per la spiaggia, ma nessuno lo degnò di uno sguardo.",
    "Contare è la cosa più aggressiva che si possa fare a un computer, è l'equivalente del guardare un essere umano con aria minacciosa ripetendo: “Sangue... sangue... sangue... sangue...”.",
    "Puoi alzarti molto presto all'alba, ma il tuo destino si è alzato un'ora prima di te.",
    "La vita non è che figura e sfondo.",
    "L'unica passione della mia vita è stata la paura.",
    "Tanto fa l'uomo che alla fine sparisce.",
    "Beati coloro che hanno fame e sete di giustizia perché saranno giustiziati.",
    "Ma il capodoglio non respira che un settimo, o una domenica, di tutto il suo tempo.",
    "Non si può parlare di Dio, perché noi siamo le parole.",
    "Wherever I am I am what is missing.",
    "No! Non avevo certo un'andatura marziale! Attraversavo come se fossi un marziano quella vita.",
    "L'uomo era solo il primo figlio di sua moglie; la chiassosa e vanagloriosa parola maschile non era in effetti che l'eco scenografica della originale e sussurrata parola femminile.",
    "Tanto che mai, e questa è stata senza dubbio la mia fortuna, la vita mi è apparsa, per essere sinceri, difficile. Complessa, certamente; impegnativa per i continui e pesanti sforzi da compiere, senza alcun dubbio.",
    "La incrollabile convinzione che la vita da adulto - la normale vita di un qualsiasi adulto - non era altro che un'affannosa e ostinata successione di traguardi e di sforzi.",
    "Nella seconda metà del Duecento in Europa centrale nascevano circa trecento città ogni decennio.",
    "Il collante di Atene derivava dal fatto che si era trasformata in una supertribù, unita dall'amore per la città, il patriottismo militante, la partecipazione democratica e l'esclusività razziale. Alessandria, nella sua vastità e diversità, era più un microcosmo del mondo.",
    "Perché gli ateniesi, che sotto i tiranni non erano militarmente superiori a nessuno dei loro vicini, ottenuta la libertà, se li lasciarono indietro a gran distanza.",
    "Per poter funzionare, la democrazia e i suoi meccanismi devono essere trasformati in un feticcio. La libertà di espressione e l'indagine senza limiti sul significato della vita rappresentano una sfida estrema per le società umane, perché sono cose pericolose e destabilizzanti. Ma questa sfida veniva accettata perché funzionava. Atene nel V secolo a.C. viaggiava a gonfie vele.",
    "È significativo che la parola araba per mercato - suq - derivi dalla parola accadica per strada - suqu - che a sua volta deriva dalla parola saqu, stretto.",
    "A Nîmes e ad Arles, la gente cercò rifugio dentro le enormi mura protettive degli anfiteatri, creando al loro interno delle cittadine.",
    "Per dimostrarmi che sono un altro, ho cambiato abitudini o per meglio dire ho cambiato ora alle mie abitudini.",
    "Svegliarsi aprendo palpebre con dita.",
    "Guardo l'ora. È trascorso un minuto.",
    "«Ecco, questi sono i suoi documenti. Lei è un mammifero, non è vero?» «Sì.» «Allora, buona poppata!»",
    "Sostegno Fuso in Oro dell'Esistere, Dottore della Perfetta Dolcezza, Universalità Luminosa, Possibilitativa.",
    "I Microcefali agricoltori lavoravano la terra, mentre quelli urbanizzati li assalivano, violentavano le loro mogli, li massacravano e li derubavano. Da ciò scaturì ben presto il commercio.",
    "Non so quanto tempo sia passato; forse un'ora, forse due. Ma che importanza può avere un'ora, due, davanti a migliaia di anni?",
    "Anche questo è catrame. Sento che sono scuse che hanno una certa validità, ma sono sempre scuse. «Ma io educo», mi dico. Di nuovo tocco il granito e mi domando: «Che nesso ci può essere fra questo granito e la carta da zucchero?»",
    "So che non so bleffare. So che mi si legge negli occhi quel sordo rancore o rabbia che si prova davanti a uno che plata soddisfatto di sé. E allora penso che questo tale si lavi i piedi, o stia seduto al gabinetto, o si spaventi all'abbaiare d'un cane, e cosí ristabilisco il mio equilibrio interiore.",
    "In questo momento io sto bruciando un certo modo d'intendere e di vivere la vita, esattamente come questo modo d'intendere e di vivere la vita viene spazzato via in questo momento dal fuoco sulla faccia della Terra.",
    "La gente come albicocche secche, gli esseri-mummia.",
    "Che aspetto aveva il Tempo? Il Tempo era come neve che cade senza rumore in una camera buia.",
    "I cani che correvano avanti, verso le solitudini che li attendevano e, improvvisamente sgomenti, tornavano con un'espressione di vuote immensità negli occhi?",
    "L'orologio parlante cantava «Tempo, tempo, tempo, tempo...» sempre con tanta delicatezza.",
    "Chi umilia è un umiliato.",
    "Finito di lavorare provo la sensazione che si prova, appunto, dopo che si è pagata una tassa.",
    "Mentre la guerra abnorme si gonfia, la nostra unità sgrana le sue ventiquattr'ore di guardia in un freddo micidiale.",
    "Trecento individui, con i volti macerati dalla stanchezza, fecero un fianco-dest e ci salutarono al grido di: «Grazie, camerati, di essere venuti anche voi!»",
    "Per quanto mi riguarda devo confessare che rido verde.",
    "E passò, con la spaventosa celerità che tutti sanno, un'altra fetta di tempo.",
    "Le parole cadranno giù a picco nel posto esattissimo come blocchi di cristallo e le onde concentriche si allargheranno ancora via per il mondo percuotendo le tenebrose scogliere.",
    "Anche le notti più felici passano senza consolarci.",
    "Tratti di prato vero, coi loro fiorellini, avevano perfino tentato di formarsi, dove stanchi noi distenderci, le braccia incrociate dietro il capo, a guardare le nuvole che passano, così libere e bianche, sopra le soperchierie degli uomini.",
    "Tenete presente che non faccio conferenze o un po' di beneficenza. Quando do, do me stesso.",
    "Tieni presente, comunque, che io sogno di continuo durante il giorno.",
    "Se non sbaglio è nella Repubblica del Niger che abbiamo trovato l'infermiera che sta in piedi nella pozzanghera con i bambini e gli insegna a dire «Blitzkrieg ist Wahnsinn»",
    "Ho chiesto se potevano individuare l'occhio umano, e gran parte degli abitanti del villaggio non erano in grado di farlo; per loro le immagini erano soltanto composizioni astratte di colore. Un uomo pensava che l'occhio fosse la finestra della capanna, e un altro ha indicato l'occhio e ha detto: «Questo è il sole che sorge».",
    "Quaggiù noi essere umani siamo la prova vivente che le cose sono andate storte.",
    "Anche se nel mio lavoro continua a essere presente una sorta di eco religiosa, la base scientifica della realtà sarà sempre più importante. Si dovrebbe evitare di frapporre un'ideologia tra noi e la nostra comprensione del pianeta. I fatti sono fatti.",
    "Dalle labbra appena accennate dello zio, dalle giunture delle dita e dalle tempie partivano nastri argentei che s'incollavano qua e là, sulla cornice degli specchi, in fondo all'argento vivo, alle fessure granulose della casse. Un filo bianco per ogni frase, come un'impalpabile sbarra.",
    "Non resta nulla, tranne la nausea e la sensazione di essermi distrutto lottando con ombre proibite.",
    "Gli diceva: «L'unica frontiera che ci rimane è il mondo dell'intangibile. Tutto il resto è cucito troppo stretto». Ingabbiato da troppe leggi.",
    "Le leggi che ci permettono di vivere sicuri sono le stesse che ci condannano alla noia. Se non possiamo accedere al caos autentico, non avremo mai autentica pace. Se le cose non hanno la possibilità di peggiorare, non migliorano.",
    "«Prendi questa montagna, ad esempio» disse. Strinse lo stupido mento del ragazzino tra il pollice e l'indice e lo fece ruotare nella direzione in cui stava guardando lei. «Questa splendida, gigantesca montagna. Per un unico, brevissimo istante, io credo di averla vista davvero.»",
    "Sono già le pettirosso e mezza, e io devo prendere l'autobus ed essere al lavoro per l'ora in cui canterà la ghiandaia.",
    "Ripiegava l'estremità penzolante della carta igienica a mo' di origami per l'utente successiva e, più in generale, tramutava il caos in ordine. Per pararti il culo, letteralmente.",
    "Una costruzione interiore, una base dove ripiegare, un territorio d'accoglienza segreto.",
    "In modo che ancora per un'ora, per due ore e mezza, per una notte, continuassero a persistere i mondi che tanto avevamo tenuto a strutturare in maniera così sofferta e a difendere.",
    "Si elabora una dichiarazione solenne, in una lingua che sembra essere la stessa dei giudici, ma che questi ultimi ascoltano con costernazione o fastidio, non essendo in grado di afferrarne il senso…",
    "Bisogna continuare a parlare senza che lui se ne avvantaggi.",
    "Al momento dei chiarimenti o delle confessioni, sempre permane una zona d'ombra che altera le confessioni al punto da renderle inutilizzabili dal nemico. Un elenco apparentemente obiettivo altro non è che un modo sarcastico per dire al nemico, una volta di più, che egli non verrà a conoscenza di nulla.",
    "Per produrre un film servono solo tre cose: un telefono, un computer e un'automobile.",
    "Secondo la radio, la guerra era ormai vinta. Ma come facevano a crederci se si vedevano mucchi di ufficiali che si bendavano per passare avanti a tutti nelle code all'infermeria?",
    "La pecora cammina. Fiuta nervosa. Sente che c'è un cristiano vicino. Pensa: «Questo mi fotte, mi tosa la lana o mi taglia la gola per mangiarmi». Ha paura. Si finge distratta.",
    "Ma combattere, combattere, in realtà non sapeva farlo nessuno. L'Esercito recluta dei buoni soldati, gli insegna più o meno a sparare, a correre, a tenere in ordine l'equipaggiamento, e con un po' di fortuna gli insegna a piantare bene la baionetta, poi però arriva la guerra e scopri che si combatte di notte, con le radio, i radar, i mirini a infrarossi, al buio, e che l'unica cosa che sai fare bene, ovvero correre, non la puoi mettere in pratica perché dietro di te, man mano che avanzi, quelli del tuo reggimento hanno piazzato delle mine. E le mine sono il peggio del peggio.",
    "Sono capaci di mollarci agli ufficiali argentini in cambio di qualcosa, qualunque cosa, e di farci fucilare. Sono uguali a loro, si trattano da pari a pari, prendono il tè insieme. Sono capaci di barattarti e farti fucilare.",
    "«Incanto inscandagliabile, quale mai vide un amante nell'occhio della giovane sposa! Non parlarmi dei tuoi squali dalle file di denti e dei tuoi modi selvaggi di rapina. Che la fede scacci i fatti, che la fantasia scacci le memorie: io guardo nel profondo e credo». E Stubb balzò come un pesce dalle scaglie scintillanti in quella stessa luce dorata: «Io sono Stubb, e Stubb ha la sua storia; ma Stubb giura qui che è sempre stato allegro!»",
    "Che cos'altro sono i Diritti dell'Uomo e le Libertà del Mondo, se non Pesce Libero? Le teste e le opinioni di tutti gli uomini? Il principio della fede religiosa in essi? I pensieri dei pensatori, per il contrabbando dei parolai pomposi? Che cos'è questo gran globo stesso altro che un Pesce Libero? E tu, lettore, che altro sei se non un Pesce Libero e un Pesce Legato insieme?",
    "Quella calma incantata che dicono si nasconda nel cuore di ogni agitazione.",
    "L'Universo reale se ne andò disgustato inarcandosi sotto di loro. Vari finti universi passarono silenziosi, come capre di montagna. Esplose la luce primordiale, spruzzando spaziotempo in giro come cucchiaiate di pannacotta. Fiorì il tempo, la materia scomparve. Il massimo numero primo si conglomerò tranquillo in un angolo e si nascose per l'eternità.",
    "Non potere impedire alle lancette dell'orologio di avvicinarsi inesorabilmente alle quattro, a quel momento fatidico che segna la fine del week-end e l'inizio della lunga oscura pausa caffè dell'anima.",
    "«È stata una cosa molto strana» disse lei, col tono con cui gli egiziani all'inseguimento degli ebrei avrebbero potuto riferirsi all'aprirsi delle acque del Mar Rosso davanti a Mosè.",
    "Abbiamo lottato per milioni di anni contro la legge di gravità.",
    "Quasi tutti i libri che ho avuto occasione di leggere in vita mia si aprono con una prefazione. Bene, allora potrò anch'io cominciare con qualcosa del genere. E dico 'del genere' perché mai e poi mai, in tutta la mia vita, quasi dal giorno in cui imparai a distinguere una femmina da un maschio, ho fatto una cosa, una qualsiasi benché minima cosa, allo stesso modo in cui la facevano i bipedi miei simili, distruttori dei beni della Natura; pertanto adesso devo, anzi vi sono tenuto per principio, scrivere in modo diverso da quello di qualsiasi altro scrittore.",
    "Assentimmo con un brivido. Alcuni di noi c'erano. Altri erano ancora lì.",
    "Se appena riesci, dopo molti minuti di errori e tentativi, o in un mezzo secondo prodigiosamente ispirato, a connetterlo con uno dei pezzi vicini, ecco che quello sparisce, cessa di esistere in quanto pezzo.",
    "Supplica la polizia che è in lui; la invoca.",
    "Occultare inutilmente il destino sotto un cumulo di bugie.",
    "Perché, concludeva borbottando fra i denti, il mondo non è fatto di porcellana e le acque da cui è bagnato, mormorava, non sono tè aromatizzati.",
    "Nascosta dietro le apparenze di un'informazione scrupolosa, la stampa, ancora una volta, ha gettato alle ortiche le questioni essenziali.",
    "Il discorso aveva lo scopo di attaccare, mediante argomentazioni allusive o polemiche, i valori sui quali il Rinascimento fondava il senso della realtà (senso dello spazio, del tempo, del tempo storico, della natura biologica dell'uomo, dell'organizzazione sociale umana).",
    "L'idea della scarsa attitudine dell'uomo a misurare il tempo, l'idea della voragine della memoria, il concetto della generale falsificazione del mondo reale e dei meccanismi che presiedevano al funzionamento della società.",
    "Non sapersi guardare nello specchio del cadavere porta alla regressione, al sonno idiota. Al silenzio della mente.",
    "Come se a un certo punto, in seguito a una rottura organica, genetica, l'uomo avesse cambiato natura.",
    "Quando la polizia apriva la pancia di qualcuno e ci ficcava dentro una granata.",
    "Sia ringraziato l'inventore della melinite, dell'acido picrico e degli altri cocktail chimici, o più semplicemente sia ringraziato lo sprovveduto che ha starnutito",
    "La convinzione che la socialdemocrazia sia in realtà un totalitarismo peggiore degli altri perché privo di incrinature,",
    "È bello oppure no, a seconda che piaccia oppure no l'odore dell'erba umida, i movimenti impercettibili del terreno trivellato, inghiottito e sminuzzato da bestiole minuscole, a seconda che piaccia oppure no il cambiamento sonoro che avviene a quell'ora, quando gli anfibi conquistano un ruolo dominante nel coro, quando le radici avanzano sotto il muschio, quando dall'orlo delle foglie ricomincia a sgocciolare l'acquerugiola. A seconda che piaccia oppure no. Io all'inizio lo detestavo.",
    "Preferimmo non fare parola tra noi di quel disastro ideologico, perché ciascuno e ciascuna di noi supponeva di avere ormai lo sguardo offuscato dalla polvere da sparo, l'animo deformato dalle lotte, e quindi di non essere la persona più adatta a giudicare,",
    "Il sole batteva a picco sul centurione senza però arrecargli il minimo danno, ed era impossibile guardare le teste di leone, perché gli occhi venivano divorati dal bagliore accecante di quell'argento che sembrava accendersi sotto il sole.",
    "Non avere mai paura di nulla. È illogico.",
    "Margherita non avrebbe saputo dire di che cosa fossero fatte le briglie del suo cavallo, e pensava che forse erano catene di luna, e il cavallo una zolla di tenebre, e la criniera del cavallo una nube, e gli speroni del cavaliere le macchie bianche delle stelle.",
    "Là in quella terra dove sopravvivono soltanto opprimenti astrazioni.",
    "Mi interrogate sul perché di questa nostalgia di un paradiso nero.",
    "A volte, sul finire del giorno, si vedevano fiocchi grigiastri uscire dalla terra e scivolare silenziosi ad altezza d'uomo, per poi svanire.",
    "Prurito cerebrale suggerente di continuo la paura della noia.",
    "La solitudine - una solitudine totale, senza un poliziotto - e il silenzio - un silenzio totale, senza la voce ammonitrice di un cortese vicino che sussurri la pubblica opinione - conducono i passi di un uomo liberi da ostacoli?",
    "Quel fanatico amore per se stessi.",
    "Che peccato, però, che non abbiano tappato le fessure e le crepe e cacciatovi un po' di filaccia qua e là. Ma è troppo tardi ora per introdurre migliorie. L'universo è finito.",
    "E se ubbidiamo a Dio, noi dobbiamo disubbidire a noi stessi, ed è in questa disubbidienza che consiste la difficoltà di ubbidire a Dio.",
    "Pentimento sincero e fedele, che non invoca il perdono, ma che è grato del castigo.",
    "Guai a colui che non volesse essere sincero, anche quando fosse salvezza essere falso!",
    "O mio Padre! ch'io conosco specialmente per la verga, io qui muoio, mortale o immortale. Mi sono sforzato di essere Tuo più che di questo mondo o di me stesso. Eppure ciò non è nulla: lascio l'eternità a Te solo, poiché che cosa è l'uomo perché debba sopravvivere a tutta la vita del suo Dio?.",
    "Finito un viaggio lunghissimo e pericolosissimo, ne comincia soltanto un secondo e, finito il secondo, ne comincia un terzo, e così via, sempre e sempre. Tale è l'interminabilità e, sì, l'intollerabilità di ogni sforzo terrestre.",
    "È già fatto. Laggiù! Il cerchio dell'orizzonte. Entro quel cerchio Caino ammazzò Abele. Bel lavoro, lavoro giusto! No? Perché allora, Signore, tu hai fatto il cerchio?",
    "E quando andiamo ancor oltre e pensiamo che il mistico cosmetico, il gran principio della luce, che produce ciascuno dei suoi colori, rimane in se stesso sempre bianco o incolore.",
    "Il caso, che sebbene costretto nell'azione tra le linee diritte della necessità e guidato obliquamente nei suoi movimenti dal libero arbitrio, sebbene così comandato dai due, a turno li comanda e dà l'ultimo colpo formatore agli eventi.",
    "E adesso fate qualcosa che valga la pena, miei pezzi d'acciaio. Datele un colpo, datele un colpo, miei figli del sole! Datele un colpo, figli di cani!",
    "Avvistato da una qualche timida nave da guerra o equivocato da una nave di scoperta, lontano, quando la distanza che offusca gli stormi di uccelli lascia tuttavia intravedere l'ammasso bianco che galleggia al sole e la schiuma bianca che vi ribolle intorno: immediatamente l'innocuo cadavere viene segnato con mano tremante nel giornale: secche, scogli e frangenti da queste parti: attenzione! E per anni, in seguito, forse, i bastimenti eviteranno quel luogo; saltandolo, come le pecore sciocche che saltano su un nulla perché una prima volta, quando qualcuno teneva là una bacchetta, la loro guida ha saltato.",
    "Non il più piccolo atomo si muove o vive nella materia, che non abbia il suo sottile riscontro nello spirito.",
    "Hanno divinizzato il coccodrillo del Nilo, perché il coccodrillo non ha lingua; e anche il capodoglio non ha lingua o, almeno, se l'ha, è tanto piccola che non può nemmeno sporgerla.",
    "Dubbi su tutte le cose terrene e intuizioni di qualcuna delle celesti.",
    "Affinchè tutti siano poeti e nessuno sia schiavo!",
    "Un bambino ogni dieci secondi, di fame.",
    "Sono stato ipotizzato.",
    "My mind contantly flows eastward.",
    "Quando Europa e Russia si combattono, altri vincono sempre.",
    "Quelle volte che torni a casa più fatto di come ne eri uscito.",
    "Tu stai con me per le cose che so, io sto con me per le cose che non so.",
    "Temer si dee di sole quelle cose c'hanno potenza di fare altrui male; de l'altre no, ché non son paurose.",
    "Far east forest.",
    "Gli aerei sono frecce di mouse, il cielo: il desktop di dio."
];